//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: message.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Method
///
/// Usage: instantiate `Message_MessageClient`, then call methods of this protocol to make API calls.
internal protocol Message_MessageClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Message_MessageClientInterceptorFactoryProtocol? { get }

  func get_messages_in_group(
    _ request: Message_GetMessagesInGroupRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Message_GetMessagesInGroupRequest, Message_GetMessagesInGroupResponse>

  func workspace_get_messages_in_group(
    _ request: Message_WorkspaceGetMessagesInGroupRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Message_WorkspaceGetMessagesInGroupRequest, Message_GetMessagesInGroupResponse>

  func subscribe(
    _ request: Message_SubscribeRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Message_SubscribeRequest, Message_BaseResponse>

  func unSubscribe(
    _ request: Message_UnSubscribeRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Message_UnSubscribeRequest, Message_BaseResponse>

  func listen(
    _ request: Message_ListenRequest,
    callOptions: CallOptions?,
    handler: @escaping (Message_MessageObjectResponse) -> Void
  ) -> ServerStreamingCall<Message_ListenRequest, Message_MessageObjectResponse>

  func publish(
    _ request: Message_PublishRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Message_PublishRequest, Message_MessageObjectResponse>

  func read_messages(
    _ request: Message_ReadMessagesRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Message_ReadMessagesRequest, Message_BaseResponse>

  func workspace_publish(
    _ request: Message_WorkspacePublishRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Message_WorkspacePublishRequest, Message_MessageObjectResponse>
}

extension Message_MessageClientProtocol {
  internal var serviceName: String {
    return "message.Message"
  }

  /// Unary call to get_messages_in_group
  ///
  /// - Parameters:
  ///   - request: Request to send to get_messages_in_group.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func get_messages_in_group(
    _ request: Message_GetMessagesInGroupRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Message_GetMessagesInGroupRequest, Message_GetMessagesInGroupResponse> {
    return self.makeUnaryCall(
      path: "/message.Message/get_messages_in_group",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeget_messages_in_groupInterceptors() ?? []
    )
  }

  /// Unary call to workspace_get_messages_in_group
  ///
  /// - Parameters:
  ///   - request: Request to send to workspace_get_messages_in_group.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func workspace_get_messages_in_group(
    _ request: Message_WorkspaceGetMessagesInGroupRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Message_WorkspaceGetMessagesInGroupRequest, Message_GetMessagesInGroupResponse> {
    return self.makeUnaryCall(
      path: "/message.Message/workspace_get_messages_in_group",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeworkspace_get_messages_in_groupInterceptors() ?? []
    )
  }

  ///action
  ///
  /// - Parameters:
  ///   - request: Request to send to Subscribe.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func subscribe(
    _ request: Message_SubscribeRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Message_SubscribeRequest, Message_BaseResponse> {
    return self.makeUnaryCall(
      path: "/message.Message/Subscribe",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSubscribeInterceptors() ?? []
    )
  }

  /// Unary call to UnSubscribe
  ///
  /// - Parameters:
  ///   - request: Request to send to UnSubscribe.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func unSubscribe(
    _ request: Message_UnSubscribeRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Message_UnSubscribeRequest, Message_BaseResponse> {
    return self.makeUnaryCall(
      path: "/message.Message/UnSubscribe",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUnSubscribeInterceptors() ?? []
    )
  }

  /// Server streaming call to Listen
  ///
  /// - Parameters:
  ///   - request: Request to send to Listen.
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ServerStreamingCall` with futures for the metadata and status.
  internal func listen(
    _ request: Message_ListenRequest,
    callOptions: CallOptions? = nil,
    handler: @escaping (Message_MessageObjectResponse) -> Void
  ) -> ServerStreamingCall<Message_ListenRequest, Message_MessageObjectResponse> {
    return self.makeServerStreamingCall(
      path: "/message.Message/Listen",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListenInterceptors() ?? [],
      handler: handler
    )
  }

  /// Unary call to Publish
  ///
  /// - Parameters:
  ///   - request: Request to send to Publish.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func publish(
    _ request: Message_PublishRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Message_PublishRequest, Message_MessageObjectResponse> {
    return self.makeUnaryCall(
      path: "/message.Message/Publish",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makePublishInterceptors() ?? []
    )
  }

  /// Unary call to read_messages
  ///
  /// - Parameters:
  ///   - request: Request to send to read_messages.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func read_messages(
    _ request: Message_ReadMessagesRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Message_ReadMessagesRequest, Message_BaseResponse> {
    return self.makeUnaryCall(
      path: "/message.Message/read_messages",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeread_messagesInterceptors() ?? []
    )
  }

  /// Unary call to workspace_publish
  ///
  /// - Parameters:
  ///   - request: Request to send to workspace_publish.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func workspace_publish(
    _ request: Message_WorkspacePublishRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Message_WorkspacePublishRequest, Message_MessageObjectResponse> {
    return self.makeUnaryCall(
      path: "/message.Message/workspace_publish",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeworkspace_publishInterceptors() ?? []
    )
  }
}

internal protocol Message_MessageClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'get_messages_in_group'.
  func makeget_messages_in_groupInterceptors() -> [ClientInterceptor<Message_GetMessagesInGroupRequest, Message_GetMessagesInGroupResponse>]

  /// - Returns: Interceptors to use when invoking 'workspace_get_messages_in_group'.
  func makeworkspace_get_messages_in_groupInterceptors() -> [ClientInterceptor<Message_WorkspaceGetMessagesInGroupRequest, Message_GetMessagesInGroupResponse>]

  /// - Returns: Interceptors to use when invoking 'subscribe'.
  func makeSubscribeInterceptors() -> [ClientInterceptor<Message_SubscribeRequest, Message_BaseResponse>]

  /// - Returns: Interceptors to use when invoking 'unSubscribe'.
  func makeUnSubscribeInterceptors() -> [ClientInterceptor<Message_UnSubscribeRequest, Message_BaseResponse>]

  /// - Returns: Interceptors to use when invoking 'listen'.
  func makeListenInterceptors() -> [ClientInterceptor<Message_ListenRequest, Message_MessageObjectResponse>]

  /// - Returns: Interceptors to use when invoking 'publish'.
  func makePublishInterceptors() -> [ClientInterceptor<Message_PublishRequest, Message_MessageObjectResponse>]

  /// - Returns: Interceptors to use when invoking 'read_messages'.
  func makeread_messagesInterceptors() -> [ClientInterceptor<Message_ReadMessagesRequest, Message_BaseResponse>]

  /// - Returns: Interceptors to use when invoking 'workspace_publish'.
  func makeworkspace_publishInterceptors() -> [ClientInterceptor<Message_WorkspacePublishRequest, Message_MessageObjectResponse>]
}

internal final class Message_MessageClient: Message_MessageClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Message_MessageClientInterceptorFactoryProtocol?

  /// Creates a client for the message.Message service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Message_MessageClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// Method
///
/// To build a server, implement a class that conforms to this protocol.
internal protocol Message_MessageProvider: CallHandlerProvider {
  var interceptors: Message_MessageServerInterceptorFactoryProtocol? { get }

  func get_messages_in_group(request: Message_GetMessagesInGroupRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Message_GetMessagesInGroupResponse>

  func workspace_get_messages_in_group(request: Message_WorkspaceGetMessagesInGroupRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Message_GetMessagesInGroupResponse>

  ///action
  func subscribe(request: Message_SubscribeRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Message_BaseResponse>

  func unSubscribe(request: Message_UnSubscribeRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Message_BaseResponse>

  func listen(request: Message_ListenRequest, context: StreamingResponseCallContext<Message_MessageObjectResponse>) -> EventLoopFuture<GRPCStatus>

  func publish(request: Message_PublishRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Message_MessageObjectResponse>

  func read_messages(request: Message_ReadMessagesRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Message_BaseResponse>

  func workspace_publish(request: Message_WorkspacePublishRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Message_MessageObjectResponse>
}

extension Message_MessageProvider {
  internal var serviceName: Substring { return "message.Message" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "get_messages_in_group":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Message_GetMessagesInGroupRequest>(),
        responseSerializer: ProtobufSerializer<Message_GetMessagesInGroupResponse>(),
        interceptors: self.interceptors?.makeget_messages_in_groupInterceptors() ?? [],
        userFunction: self.get_messages_in_group(request:context:)
      )

    case "workspace_get_messages_in_group":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Message_WorkspaceGetMessagesInGroupRequest>(),
        responseSerializer: ProtobufSerializer<Message_GetMessagesInGroupResponse>(),
        interceptors: self.interceptors?.makeworkspace_get_messages_in_groupInterceptors() ?? [],
        userFunction: self.workspace_get_messages_in_group(request:context:)
      )

    case "Subscribe":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Message_SubscribeRequest>(),
        responseSerializer: ProtobufSerializer<Message_BaseResponse>(),
        interceptors: self.interceptors?.makeSubscribeInterceptors() ?? [],
        userFunction: self.subscribe(request:context:)
      )

    case "UnSubscribe":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Message_UnSubscribeRequest>(),
        responseSerializer: ProtobufSerializer<Message_BaseResponse>(),
        interceptors: self.interceptors?.makeUnSubscribeInterceptors() ?? [],
        userFunction: self.unSubscribe(request:context:)
      )

    case "Listen":
      return ServerStreamingServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Message_ListenRequest>(),
        responseSerializer: ProtobufSerializer<Message_MessageObjectResponse>(),
        interceptors: self.interceptors?.makeListenInterceptors() ?? [],
        userFunction: self.listen(request:context:)
      )

    case "Publish":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Message_PublishRequest>(),
        responseSerializer: ProtobufSerializer<Message_MessageObjectResponse>(),
        interceptors: self.interceptors?.makePublishInterceptors() ?? [],
        userFunction: self.publish(request:context:)
      )

    case "read_messages":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Message_ReadMessagesRequest>(),
        responseSerializer: ProtobufSerializer<Message_BaseResponse>(),
        interceptors: self.interceptors?.makeread_messagesInterceptors() ?? [],
        userFunction: self.read_messages(request:context:)
      )

    case "workspace_publish":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Message_WorkspacePublishRequest>(),
        responseSerializer: ProtobufSerializer<Message_MessageObjectResponse>(),
        interceptors: self.interceptors?.makeworkspace_publishInterceptors() ?? [],
        userFunction: self.workspace_publish(request:context:)
      )

    default:
      return nil
    }
  }
}

internal protocol Message_MessageServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'get_messages_in_group'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeget_messages_in_groupInterceptors() -> [ServerInterceptor<Message_GetMessagesInGroupRequest, Message_GetMessagesInGroupResponse>]

  /// - Returns: Interceptors to use when handling 'workspace_get_messages_in_group'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeworkspace_get_messages_in_groupInterceptors() -> [ServerInterceptor<Message_WorkspaceGetMessagesInGroupRequest, Message_GetMessagesInGroupResponse>]

  /// - Returns: Interceptors to use when handling 'subscribe'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeSubscribeInterceptors() -> [ServerInterceptor<Message_SubscribeRequest, Message_BaseResponse>]

  /// - Returns: Interceptors to use when handling 'unSubscribe'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeUnSubscribeInterceptors() -> [ServerInterceptor<Message_UnSubscribeRequest, Message_BaseResponse>]

  /// - Returns: Interceptors to use when handling 'listen'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeListenInterceptors() -> [ServerInterceptor<Message_ListenRequest, Message_MessageObjectResponse>]

  /// - Returns: Interceptors to use when handling 'publish'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makePublishInterceptors() -> [ServerInterceptor<Message_PublishRequest, Message_MessageObjectResponse>]

  /// - Returns: Interceptors to use when handling 'read_messages'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeread_messagesInterceptors() -> [ServerInterceptor<Message_ReadMessagesRequest, Message_BaseResponse>]

  /// - Returns: Interceptors to use when handling 'workspace_publish'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeworkspace_publishInterceptors() -> [ServerInterceptor<Message_WorkspacePublishRequest, Message_MessageObjectResponse>]
}
