//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: note.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// gRPC methods
///
/// Usage: instantiate `Note_NoteClient`, then call methods of this protocol to make API calls.
internal protocol Note_NoteClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Note_NoteClientInterceptorFactoryProtocol? { get }

  func create_note(
    _ request: Note_CreateNoteRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Note_CreateNoteRequest, Note_UserNoteResponse>

  func edit_note(
    _ request: Note_EditNoteRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Note_EditNoteRequest, Note_BaseResponse>

  func delete_note(
    _ request: Note_DeleteNoteRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Note_DeleteNoteRequest, Note_BaseResponse>

  func get_user_notes(
    _ request: Note_GetUserNotesRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Note_GetUserNotesRequest, Note_GetUserNotesResponse>
}

extension Note_NoteClientProtocol {
  internal var serviceName: String {
    return "note.Note"
  }

  /// Unary call to create_note
  ///
  /// - Parameters:
  ///   - request: Request to send to create_note.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func create_note(
    _ request: Note_CreateNoteRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Note_CreateNoteRequest, Note_UserNoteResponse> {
    return self.makeUnaryCall(
      path: Note_NoteClientMetadata.Methods.create_note.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makecreate_noteInterceptors() ?? []
    )
  }

  /// Unary call to edit_note
  ///
  /// - Parameters:
  ///   - request: Request to send to edit_note.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func edit_note(
    _ request: Note_EditNoteRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Note_EditNoteRequest, Note_BaseResponse> {
    return self.makeUnaryCall(
      path: Note_NoteClientMetadata.Methods.edit_note.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeedit_noteInterceptors() ?? []
    )
  }

  /// Unary call to delete_note
  ///
  /// - Parameters:
  ///   - request: Request to send to delete_note.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func delete_note(
    _ request: Note_DeleteNoteRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Note_DeleteNoteRequest, Note_BaseResponse> {
    return self.makeUnaryCall(
      path: Note_NoteClientMetadata.Methods.delete_note.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makedelete_noteInterceptors() ?? []
    )
  }

  /// Unary call to get_user_notes
  ///
  /// - Parameters:
  ///   - request: Request to send to get_user_notes.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func get_user_notes(
    _ request: Note_GetUserNotesRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Note_GetUserNotesRequest, Note_GetUserNotesResponse> {
    return self.makeUnaryCall(
      path: Note_NoteClientMetadata.Methods.get_user_notes.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeget_user_notesInterceptors() ?? []
    )
  }
}

#if compiler(>=5.6)
@available(*, deprecated)
extension Note_NoteClient: @unchecked Sendable {}
#endif // compiler(>=5.6)

@available(*, deprecated, renamed: "Note_NoteNIOClient")
internal final class Note_NoteClient: Note_NoteClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Note_NoteClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Note_NoteClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the note.Note service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Note_NoteClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Note_NoteNIOClient: Note_NoteClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Note_NoteClientInterceptorFactoryProtocol?

  /// Creates a client for the note.Note service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Note_NoteClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#if compiler(>=5.6)
/// gRPC methods
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Note_NoteAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Note_NoteClientInterceptorFactoryProtocol? { get }

  func makeCreateNoteCall(
    _ request: Note_CreateNoteRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Note_CreateNoteRequest, Note_UserNoteResponse>

  func makeEditNoteCall(
    _ request: Note_EditNoteRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Note_EditNoteRequest, Note_BaseResponse>

  func makeDeleteNoteCall(
    _ request: Note_DeleteNoteRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Note_DeleteNoteRequest, Note_BaseResponse>

  func makeGetUserNotesCall(
    _ request: Note_GetUserNotesRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Note_GetUserNotesRequest, Note_GetUserNotesResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Note_NoteAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Note_NoteClientMetadata.serviceDescriptor
  }

  internal var interceptors: Note_NoteClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeCreateNoteCall(
    _ request: Note_CreateNoteRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Note_CreateNoteRequest, Note_UserNoteResponse> {
    return self.makeAsyncUnaryCall(
      path: Note_NoteClientMetadata.Methods.create_note.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makecreate_noteInterceptors() ?? []
    )
  }

  internal func makeEditNoteCall(
    _ request: Note_EditNoteRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Note_EditNoteRequest, Note_BaseResponse> {
    return self.makeAsyncUnaryCall(
      path: Note_NoteClientMetadata.Methods.edit_note.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeedit_noteInterceptors() ?? []
    )
  }

  internal func makeDeleteNoteCall(
    _ request: Note_DeleteNoteRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Note_DeleteNoteRequest, Note_BaseResponse> {
    return self.makeAsyncUnaryCall(
      path: Note_NoteClientMetadata.Methods.delete_note.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makedelete_noteInterceptors() ?? []
    )
  }

  internal func makeGetUserNotesCall(
    _ request: Note_GetUserNotesRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Note_GetUserNotesRequest, Note_GetUserNotesResponse> {
    return self.makeAsyncUnaryCall(
      path: Note_NoteClientMetadata.Methods.get_user_notes.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeget_user_notesInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Note_NoteAsyncClientProtocol {
  internal func create_note(
    _ request: Note_CreateNoteRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Note_UserNoteResponse {
    return try await self.performAsyncUnaryCall(
      path: Note_NoteClientMetadata.Methods.create_note.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makecreate_noteInterceptors() ?? []
    )
  }

  internal func edit_note(
    _ request: Note_EditNoteRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Note_BaseResponse {
    return try await self.performAsyncUnaryCall(
      path: Note_NoteClientMetadata.Methods.edit_note.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeedit_noteInterceptors() ?? []
    )
  }

  internal func delete_note(
    _ request: Note_DeleteNoteRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Note_BaseResponse {
    return try await self.performAsyncUnaryCall(
      path: Note_NoteClientMetadata.Methods.delete_note.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makedelete_noteInterceptors() ?? []
    )
  }

  internal func get_user_notes(
    _ request: Note_GetUserNotesRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Note_GetUserNotesResponse {
    return try await self.performAsyncUnaryCall(
      path: Note_NoteClientMetadata.Methods.get_user_notes.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeget_user_notesInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Note_NoteAsyncClient: Note_NoteAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Note_NoteClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Note_NoteClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#endif // compiler(>=5.6)

internal protocol Note_NoteClientInterceptorFactoryProtocol: GRPCSendable {

  /// - Returns: Interceptors to use when invoking 'create_note'.
  func makecreate_noteInterceptors() -> [ClientInterceptor<Note_CreateNoteRequest, Note_UserNoteResponse>]

  /// - Returns: Interceptors to use when invoking 'edit_note'.
  func makeedit_noteInterceptors() -> [ClientInterceptor<Note_EditNoteRequest, Note_BaseResponse>]

  /// - Returns: Interceptors to use when invoking 'delete_note'.
  func makedelete_noteInterceptors() -> [ClientInterceptor<Note_DeleteNoteRequest, Note_BaseResponse>]

  /// - Returns: Interceptors to use when invoking 'get_user_notes'.
  func makeget_user_notesInterceptors() -> [ClientInterceptor<Note_GetUserNotesRequest, Note_GetUserNotesResponse>]
}

internal enum Note_NoteClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Note",
    fullName: "note.Note",
    methods: [
      Note_NoteClientMetadata.Methods.create_note,
      Note_NoteClientMetadata.Methods.edit_note,
      Note_NoteClientMetadata.Methods.delete_note,
      Note_NoteClientMetadata.Methods.get_user_notes,
    ]
  )

  internal enum Methods {
    internal static let create_note = GRPCMethodDescriptor(
      name: "create_note",
      path: "/note.Note/create_note",
      type: GRPCCallType.unary
    )

    internal static let edit_note = GRPCMethodDescriptor(
      name: "edit_note",
      path: "/note.Note/edit_note",
      type: GRPCCallType.unary
    )

    internal static let delete_note = GRPCMethodDescriptor(
      name: "delete_note",
      path: "/note.Note/delete_note",
      type: GRPCCallType.unary
    )

    internal static let get_user_notes = GRPCMethodDescriptor(
      name: "get_user_notes",
      path: "/note.Note/get_user_notes",
      type: GRPCCallType.unary
    )
  }
}

/// gRPC methods
///
/// To build a server, implement a class that conforms to this protocol.
internal protocol Note_NoteProvider: CallHandlerProvider {
  var interceptors: Note_NoteServerInterceptorFactoryProtocol? { get }

  func create_note(request: Note_CreateNoteRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Note_UserNoteResponse>

  func edit_note(request: Note_EditNoteRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Note_BaseResponse>

  func delete_note(request: Note_DeleteNoteRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Note_BaseResponse>

  func get_user_notes(request: Note_GetUserNotesRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Note_GetUserNotesResponse>
}

extension Note_NoteProvider {
  internal var serviceName: Substring {
    return Note_NoteServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "create_note":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Note_CreateNoteRequest>(),
        responseSerializer: ProtobufSerializer<Note_UserNoteResponse>(),
        interceptors: self.interceptors?.makecreate_noteInterceptors() ?? [],
        userFunction: self.create_note(request:context:)
      )

    case "edit_note":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Note_EditNoteRequest>(),
        responseSerializer: ProtobufSerializer<Note_BaseResponse>(),
        interceptors: self.interceptors?.makeedit_noteInterceptors() ?? [],
        userFunction: self.edit_note(request:context:)
      )

    case "delete_note":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Note_DeleteNoteRequest>(),
        responseSerializer: ProtobufSerializer<Note_BaseResponse>(),
        interceptors: self.interceptors?.makedelete_noteInterceptors() ?? [],
        userFunction: self.delete_note(request:context:)
      )

    case "get_user_notes":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Note_GetUserNotesRequest>(),
        responseSerializer: ProtobufSerializer<Note_GetUserNotesResponse>(),
        interceptors: self.interceptors?.makeget_user_notesInterceptors() ?? [],
        userFunction: self.get_user_notes(request:context:)
      )

    default:
      return nil
    }
  }
}

#if compiler(>=5.6)

/// gRPC methods
///
/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Note_NoteAsyncProvider: CallHandlerProvider {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Note_NoteServerInterceptorFactoryProtocol? { get }

  @Sendable func create_note(
    request: Note_CreateNoteRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Note_UserNoteResponse

  @Sendable func edit_note(
    request: Note_EditNoteRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Note_BaseResponse

  @Sendable func delete_note(
    request: Note_DeleteNoteRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Note_BaseResponse

  @Sendable func get_user_notes(
    request: Note_GetUserNotesRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Note_GetUserNotesResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Note_NoteAsyncProvider {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Note_NoteServerMetadata.serviceDescriptor
  }

  internal var serviceName: Substring {
    return Note_NoteServerMetadata.serviceDescriptor.fullName[...]
  }

  internal var interceptors: Note_NoteServerInterceptorFactoryProtocol? {
    return nil
  }

  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "create_note":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Note_CreateNoteRequest>(),
        responseSerializer: ProtobufSerializer<Note_UserNoteResponse>(),
        interceptors: self.interceptors?.makecreate_noteInterceptors() ?? [],
        wrapping: self.create_note(request:context:)
      )

    case "edit_note":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Note_EditNoteRequest>(),
        responseSerializer: ProtobufSerializer<Note_BaseResponse>(),
        interceptors: self.interceptors?.makeedit_noteInterceptors() ?? [],
        wrapping: self.edit_note(request:context:)
      )

    case "delete_note":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Note_DeleteNoteRequest>(),
        responseSerializer: ProtobufSerializer<Note_BaseResponse>(),
        interceptors: self.interceptors?.makedelete_noteInterceptors() ?? [],
        wrapping: self.delete_note(request:context:)
      )

    case "get_user_notes":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Note_GetUserNotesRequest>(),
        responseSerializer: ProtobufSerializer<Note_GetUserNotesResponse>(),
        interceptors: self.interceptors?.makeget_user_notesInterceptors() ?? [],
        wrapping: self.get_user_notes(request:context:)
      )

    default:
      return nil
    }
  }
}

#endif // compiler(>=5.6)

internal protocol Note_NoteServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'create_note'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makecreate_noteInterceptors() -> [ServerInterceptor<Note_CreateNoteRequest, Note_UserNoteResponse>]

  /// - Returns: Interceptors to use when handling 'edit_note'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeedit_noteInterceptors() -> [ServerInterceptor<Note_EditNoteRequest, Note_BaseResponse>]

  /// - Returns: Interceptors to use when handling 'delete_note'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makedelete_noteInterceptors() -> [ServerInterceptor<Note_DeleteNoteRequest, Note_BaseResponse>]

  /// - Returns: Interceptors to use when handling 'get_user_notes'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeget_user_notesInterceptors() -> [ServerInterceptor<Note_GetUserNotesRequest, Note_GetUserNotesResponse>]
}

internal enum Note_NoteServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Note",
    fullName: "note.Note",
    methods: [
      Note_NoteServerMetadata.Methods.create_note,
      Note_NoteServerMetadata.Methods.edit_note,
      Note_NoteServerMetadata.Methods.delete_note,
      Note_NoteServerMetadata.Methods.get_user_notes,
    ]
  )

  internal enum Methods {
    internal static let create_note = GRPCMethodDescriptor(
      name: "create_note",
      path: "/note.Note/create_note",
      type: GRPCCallType.unary
    )

    internal static let edit_note = GRPCMethodDescriptor(
      name: "edit_note",
      path: "/note.Note/edit_note",
      type: GRPCCallType.unary
    )

    internal static let delete_note = GRPCMethodDescriptor(
      name: "delete_note",
      path: "/note.Note/delete_note",
      type: GRPCCallType.unary
    )

    internal static let get_user_notes = GRPCMethodDescriptor(
      name: "get_user_notes",
      path: "/note.Note/get_user_notes",
      type: GRPCCallType.unary
    )
  }
}
