//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: workspace.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Workspace_WorkspaceClient`, then call methods of this protocol to make API calls.
internal protocol Workspace_WorkspaceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Workspace_WorkspaceClientInterceptorFactoryProtocol? { get }

  func workspace_info(
    _ request: Workspace_WorkspaceInfoRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Workspace_WorkspaceInfoRequest, Workspace_WorkspaceInfoResponse>

  func leave_workspace(
    _ request: Workspace_LeaveWorkspaceRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Workspace_LeaveWorkspaceRequest, Workspace_BaseResponse>
}

extension Workspace_WorkspaceClientProtocol {
  internal var serviceName: String {
    return "workspace.Workspace"
  }

  /// Unary call to workspace_info
  ///
  /// - Parameters:
  ///   - request: Request to send to workspace_info.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func workspace_info(
    _ request: Workspace_WorkspaceInfoRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Workspace_WorkspaceInfoRequest, Workspace_WorkspaceInfoResponse> {
    return self.makeUnaryCall(
      path: Workspace_WorkspaceClientMetadata.Methods.workspace_info.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeworkspace_infoInterceptors() ?? []
    )
  }

  /// Unary call to leave_workspace
  ///
  /// - Parameters:
  ///   - request: Request to send to leave_workspace.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func leave_workspace(
    _ request: Workspace_LeaveWorkspaceRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Workspace_LeaveWorkspaceRequest, Workspace_BaseResponse> {
    return self.makeUnaryCall(
      path: Workspace_WorkspaceClientMetadata.Methods.leave_workspace.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeleave_workspaceInterceptors() ?? []
    )
  }
}

#if compiler(>=5.6)
@available(*, deprecated)
extension Workspace_WorkspaceClient: @unchecked Sendable {}
#endif // compiler(>=5.6)

@available(*, deprecated, renamed: "Workspace_WorkspaceNIOClient")
internal final class Workspace_WorkspaceClient: Workspace_WorkspaceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Workspace_WorkspaceClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Workspace_WorkspaceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the workspace.Workspace service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Workspace_WorkspaceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Workspace_WorkspaceNIOClient: Workspace_WorkspaceClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Workspace_WorkspaceClientInterceptorFactoryProtocol?

  /// Creates a client for the workspace.Workspace service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Workspace_WorkspaceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#if compiler(>=5.6)
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Workspace_WorkspaceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Workspace_WorkspaceClientInterceptorFactoryProtocol? { get }

  func makeWorkspaceInfoCall(
    _ request: Workspace_WorkspaceInfoRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Workspace_WorkspaceInfoRequest, Workspace_WorkspaceInfoResponse>

  func makeLeaveWorkspaceCall(
    _ request: Workspace_LeaveWorkspaceRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Workspace_LeaveWorkspaceRequest, Workspace_BaseResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Workspace_WorkspaceAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Workspace_WorkspaceClientMetadata.serviceDescriptor
  }

  internal var interceptors: Workspace_WorkspaceClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeWorkspaceInfoCall(
    _ request: Workspace_WorkspaceInfoRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Workspace_WorkspaceInfoRequest, Workspace_WorkspaceInfoResponse> {
    return self.makeAsyncUnaryCall(
      path: Workspace_WorkspaceClientMetadata.Methods.workspace_info.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeworkspace_infoInterceptors() ?? []
    )
  }

  internal func makeLeaveWorkspaceCall(
    _ request: Workspace_LeaveWorkspaceRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Workspace_LeaveWorkspaceRequest, Workspace_BaseResponse> {
    return self.makeAsyncUnaryCall(
      path: Workspace_WorkspaceClientMetadata.Methods.leave_workspace.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeleave_workspaceInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Workspace_WorkspaceAsyncClientProtocol {
  internal func workspace_info(
    _ request: Workspace_WorkspaceInfoRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Workspace_WorkspaceInfoResponse {
    return try await self.performAsyncUnaryCall(
      path: Workspace_WorkspaceClientMetadata.Methods.workspace_info.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeworkspace_infoInterceptors() ?? []
    )
  }

  internal func leave_workspace(
    _ request: Workspace_LeaveWorkspaceRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Workspace_BaseResponse {
    return try await self.performAsyncUnaryCall(
      path: Workspace_WorkspaceClientMetadata.Methods.leave_workspace.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeleave_workspaceInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Workspace_WorkspaceAsyncClient: Workspace_WorkspaceAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Workspace_WorkspaceClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Workspace_WorkspaceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#endif // compiler(>=5.6)

internal protocol Workspace_WorkspaceClientInterceptorFactoryProtocol: GRPCSendable {

  /// - Returns: Interceptors to use when invoking 'workspace_info'.
  func makeworkspace_infoInterceptors() -> [ClientInterceptor<Workspace_WorkspaceInfoRequest, Workspace_WorkspaceInfoResponse>]

  /// - Returns: Interceptors to use when invoking 'leave_workspace'.
  func makeleave_workspaceInterceptors() -> [ClientInterceptor<Workspace_LeaveWorkspaceRequest, Workspace_BaseResponse>]
}

internal enum Workspace_WorkspaceClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Workspace",
    fullName: "workspace.Workspace",
    methods: [
      Workspace_WorkspaceClientMetadata.Methods.workspace_info,
      Workspace_WorkspaceClientMetadata.Methods.leave_workspace,
    ]
  )

  internal enum Methods {
    internal static let workspace_info = GRPCMethodDescriptor(
      name: "workspace_info",
      path: "/workspace.Workspace/workspace_info",
      type: GRPCCallType.unary
    )

    internal static let leave_workspace = GRPCMethodDescriptor(
      name: "leave_workspace",
      path: "/workspace.Workspace/leave_workspace",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Workspace_WorkspaceProvider: CallHandlerProvider {
  var interceptors: Workspace_WorkspaceServerInterceptorFactoryProtocol? { get }

  func workspace_info(request: Workspace_WorkspaceInfoRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Workspace_WorkspaceInfoResponse>

  func leave_workspace(request: Workspace_LeaveWorkspaceRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Workspace_BaseResponse>
}

extension Workspace_WorkspaceProvider {
  internal var serviceName: Substring {
    return Workspace_WorkspaceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "workspace_info":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Workspace_WorkspaceInfoRequest>(),
        responseSerializer: ProtobufSerializer<Workspace_WorkspaceInfoResponse>(),
        interceptors: self.interceptors?.makeworkspace_infoInterceptors() ?? [],
        userFunction: self.workspace_info(request:context:)
      )

    case "leave_workspace":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Workspace_LeaveWorkspaceRequest>(),
        responseSerializer: ProtobufSerializer<Workspace_BaseResponse>(),
        interceptors: self.interceptors?.makeleave_workspaceInterceptors() ?? [],
        userFunction: self.leave_workspace(request:context:)
      )

    default:
      return nil
    }
  }
}

#if compiler(>=5.6)

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Workspace_WorkspaceAsyncProvider: CallHandlerProvider {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Workspace_WorkspaceServerInterceptorFactoryProtocol? { get }

  @Sendable func workspace_info(
    request: Workspace_WorkspaceInfoRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Workspace_WorkspaceInfoResponse

  @Sendable func leave_workspace(
    request: Workspace_LeaveWorkspaceRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Workspace_BaseResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Workspace_WorkspaceAsyncProvider {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Workspace_WorkspaceServerMetadata.serviceDescriptor
  }

  internal var serviceName: Substring {
    return Workspace_WorkspaceServerMetadata.serviceDescriptor.fullName[...]
  }

  internal var interceptors: Workspace_WorkspaceServerInterceptorFactoryProtocol? {
    return nil
  }

  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "workspace_info":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Workspace_WorkspaceInfoRequest>(),
        responseSerializer: ProtobufSerializer<Workspace_WorkspaceInfoResponse>(),
        interceptors: self.interceptors?.makeworkspace_infoInterceptors() ?? [],
        wrapping: self.workspace_info(request:context:)
      )

    case "leave_workspace":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Workspace_LeaveWorkspaceRequest>(),
        responseSerializer: ProtobufSerializer<Workspace_BaseResponse>(),
        interceptors: self.interceptors?.makeleave_workspaceInterceptors() ?? [],
        wrapping: self.leave_workspace(request:context:)
      )

    default:
      return nil
    }
  }
}

#endif // compiler(>=5.6)

internal protocol Workspace_WorkspaceServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'workspace_info'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeworkspace_infoInterceptors() -> [ServerInterceptor<Workspace_WorkspaceInfoRequest, Workspace_WorkspaceInfoResponse>]

  /// - Returns: Interceptors to use when handling 'leave_workspace'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeleave_workspaceInterceptors() -> [ServerInterceptor<Workspace_LeaveWorkspaceRequest, Workspace_BaseResponse>]
}

internal enum Workspace_WorkspaceServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Workspace",
    fullName: "workspace.Workspace",
    methods: [
      Workspace_WorkspaceServerMetadata.Methods.workspace_info,
      Workspace_WorkspaceServerMetadata.Methods.leave_workspace,
    ]
  )

  internal enum Methods {
    internal static let workspace_info = GRPCMethodDescriptor(
      name: "workspace_info",
      path: "/workspace.Workspace/workspace_info",
      type: GRPCCallType.unary
    )

    internal static let leave_workspace = GRPCMethodDescriptor(
      name: "leave_workspace",
      path: "/workspace.Workspace/leave_workspace",
      type: GRPCCallType.unary
    )
  }
}
